version: '3'
services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_SURL_API_HTTP_URL: http://localhost:3000
        REACT_APP_SURL_API_WS_URL: ws://localhost:4000
    ports:
    - "8080:80"
  backend:
    build: ./backend
    depends_on:
    - mongodb
    command: ["/bin/bash", "./wait-for-it.sh", "mongodb:27017", "--", "yarn", "start"]
    environment:
      SURL_DB_HOST: mongodb
      SURL_DB_PORT: 27017
      SURL_DB_NAME: surl
    ports:
    - "3000:3000"
    - "4000:4000"
  mongodb:
    image: 'mongo'
